"""Generates the Unicode data Metaglyph bundles, from the Unicode
Character Database. Run from the repository root:

    python scripts/unicode-data.py

Writes:
- editors/web/src/data/unicode-names.txt: `HEX;NAME` per named character,
  for the 01 sheet's character search. Controls and the algorithmically
  named ranges (CJK ideographs, Hangul syllables, Tangut, ...) are left
  out; those are found by codepoint or by pasting the character.
- editors/web/src/data/variation-sequences.txt: `BASE SELECTOR;DESCRIPTION`
  per standardized and emoji variation sequence, for the same search.
- crates/mg-font/src/sequences.rs: the same sequences as a sorted Rust
  table, for the spec §10.6 warning on a VS1-VS16 sequence Unicode does not
  standardize.
"""

import io
import urllib.request

VERSION = "16.0.0"
UCD = f"https://www.unicode.org/Public/{VERSION}/ucd"


def fetch(path):
    with urllib.request.urlopen(f"{UCD}/{path}") as response:
        return response.read().decode("utf-8").splitlines()


def write(path, text):
    with io.open(path, "w", encoding="utf-8", newline="\n") as out:
        out.write(text)
    print(f"wrote {path}")


def is_selector(cp):
    return 0xFE00 <= cp <= 0xFE0F or 0xE0100 <= cp <= 0xE01EF


# Character names.
names = {}
lines = [f"# Unicode {VERSION} character names, from {UCD}/UnicodeData.txt"]
for line in fetch("UnicodeData.txt"):
    cp, name = line.split(";")[:2]
    if not name.startswith("<"):
        names[int(cp, 16)] = name
        lines.append(f"{cp};{name}")
write("editors/web/src/data/unicode-names.txt", "\n".join(lines) + "\n")

# Variation sequences: `BASE SELECTOR; description; ...`. Mongolian free
# variation selectors (U+180B-U+180F) are not variation selectors in
# spec §5.6's sense, so their sequences are left out.
sequences = {}
for source in ["StandardizedVariants.txt", "emoji/emoji-variation-sequences.txt"]:
    for line in fetch(source):
        line = line.split("#")[0].strip()
        if not line:
            continue
        fields = [f.strip() for f in line.split(";")]
        base, selector = (int(c, 16) for c in fields[0].split())
        if is_selector(selector):
            description = fields[1]
            if len(fields) > 2 and fields[2]:
                description += f" ({fields[2]})"
            sequences.setdefault((base, selector), description)

lines = [f"# Unicode {VERSION} standardized and emoji variation sequences"]
for (base, selector), description in sorted(sequences.items()):
    lines.append(f"{base:04X} {selector:04X};{description}")
write("editors/web/src/data/variation-sequences.txt", "\n".join(lines) + "\n")

rows = "\n".join(f"    (0x{b:04X}, 0x{s:04X})," for b, s in sorted(sequences))
write(
    "crates/mg-font/src/sequences.rs",
    f"""//! Unicode {VERSION}'s standardized and emoji variation sequences, as
//! `(base, selector)` sorted ascending. Generated by
//! `scripts/unicode-data.py`; do not edit.

pub const STANDARDIZED: &[(u32, u32)] = &[
{rows}
];
""",
)
print(f"{len(names)} names, {len(sequences)} sequences")
